insert into user (idUser, nome, email, senha, telCel, dataCriacao) values (null, 'Carlos', 'carlos@casa.com.br', '12345678', '11987654396', null);
insert into user (idUser, nome, email, senha, telCel, dataCriacao) values (null, 'Fernando', 'fernando@casa.com.br', '12345678', '11987654333', null);
insert into user (idUser, nome, email, senha, telCel, dataCriacao) values (null, 'Flagner', 'flagner@casa.com.br', '12345678', '41987654396', null);

insert into categoria (idCategoria, nomeCat, dataCriacao) values (null, 'Gastronomia', null);
insert into categoria (idCategoria, nomeCat, dataCriacao) values (null, 'Hospedagem', null);
insert into categoria (idCategoria, nomeCat, dataCriacao) values (null, 'Passeios', null);
insert into categoria (idCategoria, nomeCat, dataCriacao) values (null, 'Roteiros', null);
insert into categoria (idCategoria, nomeCat, dataCriacao) values (null, 'Passeios', null);

insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Bares/Lanches', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Cafés/Docerias', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Cozinha Brasileira', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Cozinha Internacional', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Pizzarias', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Quiosques', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Demais Segmentos', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Hotéis', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Hotéis Fazenda', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Motéis', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Pousadas', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Resorts', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Campings', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Compras', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Cultura', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Lazer', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Agências de Turismo', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Aventuras', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Destilarias', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Equestres', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Flores e Frutas', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Pesqueiros', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Religioso', null);
insert into subCat (idSubCat, nomeSubCat, dataCriacao) values (null, 'Rural', null);

insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null, 'ACESSIBILIDADE', 'Cadeirante', 'fa-wheelchair', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null, 'ACESSIBILIDADE', 'Def.Visual', 'fa-blind', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ACESSIBILIDADE', 'Def.Auditivo', 'fa-deaf', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ACEITA CARTÕES', 'Amex', 'fa-cc-amex', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ACEITA CARTÕES', 'Visa', 'fa-cc-visa', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ACEITA CARTÕES', 'Diners', 'fa-cc-diners-club', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ACEITA CARTÕES', 'MasterCard', 'fa-cc-mastercard', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ALIMENTAÇÃO', 'Adega de Vinho', 'fa-wine-bottle', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ALIMENTAÇÃO', 'Bar', 'fa-cocktail', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ALIMENTAÇÃO', 'Restaurante', 'fa-utensils', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'ALIMENTAÇÃO', 'Café Manha Incluso', 'fa-coffee', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Aceita-se pets', 'fa-paw', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Estacionamento', 'fa-parking', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Ar-condicionado', 'fa-snowflake', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Wifi', 'fa-wifi', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Carregador Malas', 'fa-luggage-cart', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Espaço Saúde', 'fa-spa', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Frigobar', 'fa-refrigerator', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Não Fumante', 'fa-smoking-ban', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Piscina', 'fa-swimming-pool', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Salão fitness', 'fa-dumbbell', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'CONVENIÊNCIAS', 'Serviço de Quarto', 'fa-concierge-bell', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REDES SOCIAIS', 'Facebook', 'fa-facebook-square', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REDES SOCIAIS', 'Instagram', 'fa-Instagram', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REDES SOCIAIS', 'Site', 'fa-globe', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REFERÊNCIA', 'Estrelas', 'fa-star', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REFERÊNCIA', 'Positivo', 'fa-thumbs-up', null);
insert into servico (idServico, nomeServico, tipoServico, iconServico, dataCriacao) values (null , 'REFERÊNCIA',	'$$$ Cifrão' ,'fa-dollar-sign', null);
